# Actual Shipping API for FBEv1
  PRODUCT_SHIPPING_API_LEVEL := 28

# fscrypt policy
   TW_USE_FSCRYPT_POLICY := 1

# Default FS type
BOARD_USERDATAIMAGE_FILE_SYSTEM_TYPE := ext4

#Platform
PLATFORM_VERSION := 16.1.0
PLATFORM_SECURITY_PATCH := 2099-12-31
VENDOR_SECURITY_PATCH := $(PLATFORM_SECURITY_PATCH)
PLATFORM_VERSION_LAST_STABLE := $(PLATFORM_VERSION)
BOOT_SECURITY_PATCH := $(PLATFORM_SECURITY_PATCH)

# Prebuilt Kernel
TARGET_PREBUILT_KERNEL := $(DEVICE_PATH)/prebuilt/FBEv1/Image.gz-dtb
BOARD_PREBUILT_DTBOIMAGE := $(DEVICE_PATH)/prebuilt/FBEv1/dtbo.img

# Fstab and flags
TARGET_RECOVERY_FSTAB := $(DEVICE_PATH)/fstab/recovery-fbev1.fstab
PRODUCT_COPY_FILES += $(DEVICE_PATH)/fstab/wrappedkey.fstab:$(TARGET_COPY_OUT_RECOVERY)/root/system/etc/wrappedkey.fstab
PRODUCT_COPY_FILES += $(DEVICE_PATH)/fstab/twrp-fbev1.flags:$(TARGET_COPY_OUT_RECOVERY)/root/system/etc/twrp.flags